### ISSUE TITLE
Import various formats into Prejournal (milestone 1a)

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#26]
See https://github.com/federatedbookkeeping/timesheets/blob/main/README.md#milestone-1-prejournal

**Comment by michielbdejong** [comment]
Was that comment meant to go onto #28 and/or #29 probably?

**Comment by michielbdejong** [comment]
> Milestone 1: Prejournal
Prejournal.org will be a headless bookkeeping connector that can take data from many types of source documents and export data to many different bookkeeping tools. It can be run as a stand-alone LAMP application, or as a Nextcloud app.
>
> Deliverable: Tagged release of the code that does the following.
1a - 6000 EUR) Import timesheets data from the timetracker tools listed in the wiki (4) that allow data retrieval, either through an API or through a manual export-and-import flow, as well as relevant open standards (like caldav etc).

To do:
* [ ] [ability to run Prejournal as a Nextcloud app](https://github.com/pondersource/prejournal/issues/135)
* [ ] screencast: import timesheets data from Timeld-CLI
* [ ] screencast: import timesheets data from Evoludata-GUI
* [ ] screencast: import timesheets data from [Mite CMD](https://github.com/Overbryd/mite.cmd)
* [ ] screencast: import timesheets data from [Savemytime](https://play.google.com/store/apps/details?id=com.godmodev.optime)
* [ ] screencast: import timesheets data from [Scoro](https://www.scoro.com/time-management-software/)
* [ ] screencast: import timesheets data from [Stratustime](https://stratustime.centralservers.com/)
* [ ] screencast: import timesheets data from [Time](https://github.com/wbbly/time)
* [ ] screencast: import timesheets data from [TimeBro](https://www.timebro.com/)
* [ ] screencast: import timesheets data from [Timecamp](https://www.timecamp.com/)
* [ ] screencast: import timesheets data from [Time Doctor](https://www.timedoctor.com/)
* [ ] screencast: import timesheets data from [Timely](https://www.freshworks.com/apps/freshdesk/timely/)
* [ ] screencast: import timesheets data from [Time Manager](https://apps.nextcloud.com/apps/timemanager)
* [ ] screencast: import timesheets data from [Timesheet](https://play.google.com/store/apps/details?id=robin.urenapp)
* [ ] screencast: import timesheets data from [Timesheet Mobile](https://apps.apple.com/us/app/timesheet-mobile/id560462162)
* [ ] screencast: import timesheets data from Timesheets Time Tracker (see Veryfi)
* [ ] screencast: import timesheets data from [Timetip](https://github.com/rstacruz/timetip)
* [ ] screencast: import timesheets data from [Timetracker](https://github.com/anuko/timetracker)
* [ ] screencast: import timesheets data from [Time Tracker CLI](https://github.com/danibram/time-tracker-cli)
* [ ] screencast: import timesheets data from [Time Tracker](https://play.google.com/store/apps/details?id=com.cg.android.ebillitytimetracker)
* [ ] screencast: import timesheets data from [Time Tracker](https://apps.nextcloud.com/apps/timetracker)

**Comment by michielbdejong** [comment]
One screencast could show how the pondersource-books/time repo works:
* explain that normally Timeld-org and timesheet-dev3-evoludata-com push immediately, but in case of disaster, we can use Prejournal's import functionality to pull in data from both with a single command
* empty time.pondersource.com
* show report
* run recovery script
* show report

Another would show the csv-based imports.

**Comment by michielbdejong** [comment]
I realised the "reset script" demo can use curl because it's sysadmin-facing
But the csv-imports demo needs to be using manual file upload through the Nextcloud GUI.
Setting that up now in https://github.com/pondersource/prejournal/pull/136

**Comment by michielbdejong** [comment]
Done, see #52
