### ISSUE TITLE
milestone 4 wrap up

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#43]
Given we're already way over budget, and we have a pretty good list of apps and formats now, it's probably time to wrap up [milestone 4](https://github.com/federatedbookkeeping/timesheets#milestone-4-documentation). To do this, I will:

* [x] clean up the apps list
* [x] clean up the data formats list
* [x] clean up the glossary
* [x] write a summary of our latest tier 1 / tier 2 thinking
* [x] write up which tier 2 system can sync with which tier 1 system, and in which way(s)

This shouldn't stop anyone else from doing other documentation work! Just want to make sure our documentation is at the level where we can feel confident to send the Request for Payment for it.

**Comment by michielbdejong** [comment]
I think WikiSuite and Prejournal can mostly import from existing timetracker apps, and export only to Scoro. I left this underspecified in the current text. Will update as and when I find more info on that.

**Comment by Angus-McAllister** [comment]
I'm happy to contribute to the "write a summary of our latest tier 1 / tier 2 thinking" step mentioned above.

**Comment by michielbdejong** [comment]
@Angus-McAllister great! Please edit https://github.com/federatedbookkeeping/timesheets#timesheets

**Comment by michielbdejong** [comment]
I was a bit doubtful of whether to use the term "the club" or the term "Tier 2", in the end I used them both which might not be optimal. Please feel free to rework the paragraph, add your diagrams, etc!

**Comment by Angus-McAllister** [comment]
I've been reflecting on the tier naming convention, and I think we should reconsider this.  Here's why: within "the club" of federated systems, if the number of point-to-point integrations increases beyond a manageable level for one or more systems, some of them could take on a more official "proxy" role for others (as all of those in the club do for those _outside_ it).  They would hence be in effect a different tier.  Similar to how Autonomous Systems work for routing on the Internet, there could be additional tiers for these.

Perhaps those outside the club could be called "Outer Systems" or "External Systems", those at the edge providing connectivity between External Systems and the federation could be "Gateway Members", and those acting as go-betweens be "Federation Proxy Members" (with tiering for these in particular for large-scale examples).  I'm not that precious about the exact naming; it's more that the convention should have room for expansion should it be needed.
